"""
LocalLens — PDF Report Generator
==================================
Generates a professionally branded PDF report from photo folder analysis data.
Called by the /api/export-report endpoint in main.py.
"""

import os
import logging
from datetime import datetime
from typing import Dict, List, Optional, Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas as pdf_canvas
from reportlab.lib.utils import ImageReader


# ── Color palette ──
CLR_DARK   = HexColor("#1a1a2e")
CLR_ACCENT = HexColor("#6c63ff")
CLR_TEXT   = HexColor("#2d2d2d")
CLR_MUTED  = HexColor("#6b7280")
CLR_WHITE  = HexColor("#ffffff")
CLR_LINE   = HexColor("#e5e7eb")
CLR_BAR_BG = HexColor("#f3f4f6")
CLR_AMBER  = HexColor("#f59e0b")
CLR_GREEN  = HexColor("#10b981")
CLR_BLUE   = HexColor("#3b82f6")
CLR_PURPLE = HexColor("#8b5cf6")
CLR_BRAND  = HexColor("#a5a3ff")   # Soft accent for brand text

MONTH_NAMES = {
    "01": "Jan", "02": "Feb", "03": "Mar", "04": "Apr",
    "05": "May", "06": "Jun", "07": "Jul", "08": "Aug",
    "09": "Sep", "10": "Oct", "11": "Nov", "12": "Dec",
}


def generate_report_pdf(
    output_path: str,
    source_folder: str,
    folder_name: str,
    app_version: str,
    file_count: int,
    total_size_bytes: int,
    extension_counts: Dict[str, int],
    subfolder_count: int,
    subfolder_list: List[str],
    ignore_set: set,
    locations: List[str],
    date_info: Dict[str, Any],
    people: List[str],
    logo_path: Optional[str] = None,
) -> None:
    """
    Renders the report data into a branded A4 PDF and saves it to `output_path`.
    Raises on failure — the caller should catch and return an HTTP error.
    """
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    page_w, page_h = A4
    margin = 25 * mm
    content_w = page_w - 2 * margin
    generated_at = datetime.now()

    cv = pdf_canvas.Canvas(output_path, pagesize=A4)
    cv.setTitle(f"{folder_name} — Photo Album Report")
    cv.setAuthor("LocalLens")
    cv.setSubject(f"Analysis of {source_folder}")

    # ── Mutable cursor ──
    y_cursor = [page_h]

    # ------------------------------------------------------------------
    #  Drawing helpers (closures over cv, y_cursor, margin, page_w, etc.)
    # ------------------------------------------------------------------

    def _y():
        return y_cursor[0]

    def _set_y(val):
        y_cursor[0] = val

    def _move(delta):
        y_cursor[0] -= delta

    def _footer():
        cv.saveState()
        cv.setStrokeColor(CLR_LINE)
        cv.setLineWidth(0.3)
        cv.line(margin, 14 * mm, page_w - margin, 14 * mm)
        cv.setFont("Helvetica", 6.5)
        cv.setFillColor(CLR_MUTED)
        cv.drawString(margin, 10 * mm, f"Generated by LocalLens v{app_version}")
        cv.drawRightString(
            page_w - margin, 10 * mm,
            generated_at.strftime("%d %b %Y, %H:%M"),
        )
        cv.restoreState()

    def _check_page(needed=40):
        if _y() < margin + needed:
            _footer()
            cv.showPage()
            _set_y(page_h - margin)

    def _section(title, color=CLR_ACCENT):
        _check_page(55)
        _move(22)
        cv.setFillColor(color)
        cv.roundRect(margin, _y() - 2, 3.5, 15, 1.5, fill=1, stroke=0)
        cv.setFont("Helvetica-Bold", 12)
        cv.setFillColor(CLR_TEXT)
        cv.drawString(margin + 11, _y(), title)
        _move(7)
        cv.setStrokeColor(CLR_LINE)
        cv.setLineWidth(0.4)
        cv.line(margin, _y(), page_w - margin, _y())
        _move(16)

    def _kv(label, value, indent=0):
        _check_page(16)
        cv.setFont("Helvetica", 8.5)
        cv.setFillColor(CLR_MUTED)
        cv.drawString(margin + 12 + indent, _y(), label)
        cv.setFont("Helvetica-Bold", 8.5)
        cv.setFillColor(CLR_TEXT)
        cv.drawString(margin + 115 + indent, _y(), str(value))
        _move(15)

    def _bullet(text, color=CLR_ACCENT):
        _check_page(15)
        cv.setFillColor(color)
        cv.circle(margin + 15, _y() + 2.5, 2, fill=1, stroke=0)
        cv.setFont("Helvetica", 8.5)
        cv.setFillColor(CLR_TEXT)
        cv.drawString(margin + 23, _y(), text)
        _move(15)

    # ==================================================================
    #  PAGE HEADER
    # ==================================================================
    header_h = 80

    # Dark background band
    cv.setFillColor(CLR_DARK)
    cv.rect(0, page_h - header_h, page_w, header_h, fill=1, stroke=0)

    # Accent stripe below header
    cv.setFillColor(CLR_ACCENT)
    cv.rect(0, page_h - header_h - 2.5, page_w, 2.5, fill=1, stroke=0)

    # Logo + "LocalLens" — small, top-left within the header
    brand_label_y = page_h - 26
    brand_x = margin
    if logo_path and os.path.isfile(logo_path):
        try:
            logo_img = ImageReader(logo_path)
            cv.drawImage(
                logo_img, margin, brand_label_y - 4,
                width=14, height=14,
                preserveAspectRatio=True, mask="auto",
            )
            brand_x = margin + 18
        except Exception:
            pass  # Graceful — skip logo on error
    cv.setFont("Helvetica", 7)
    cv.setFillColor(CLR_BRAND)
    cv.drawString(brand_x, brand_label_y, "LocalLens")

    # Main title
    cv.setFont("Helvetica-Bold", 22)
    cv.setFillColor(CLR_WHITE)
    cv.drawString(margin, page_h - header_h + 18, "Photo Album Report")

    _set_y(page_h - header_h - 20)

    # ── Source path & generation timestamp ──
    cv.setFont("Helvetica", 7.5)
    cv.setFillColor(CLR_MUTED)
    cv.drawString(margin, _y(), "Source")
    cv.drawString(page_w / 2, _y(), "Generated")
    _move(12)

    cv.setFont("Helvetica-Bold", 8)
    cv.setFillColor(CLR_TEXT)
    display_path = source_folder
    if len(display_path) > 65:
        display_path = "..." + display_path[-62:]
    cv.drawString(margin, _y(), display_path)

    cv.setFont("Helvetica", 8)
    cv.setFillColor(CLR_MUTED)
    cv.drawString(page_w / 2, _y(), generated_at.strftime("%d %B %Y, %H:%M"))
    _move(22)

    # ==================================================================
    #  SUMMARY
    # ==================================================================
    _section("Summary")

    total_mb = round(total_size_bytes / (1024 * 1024), 2)
    _kv("Total Photos", f"{file_count:,}")
    _kv("Total Size", f"{total_mb:,.2f} MB")
    _kv("Subfolders", str(subfolder_count))
    if ignore_set:
        _kv("Ignored Folders", str(len(ignore_set)))
    if locations:
        _kv("Locations Found", str(len(locations)))
    if people:
        _kv("Enrolled People", str(len(people)))
    if date_info:
        years = sorted(date_info.keys())
        if len(years) > 1:
            _kv("Date Range", f"{years[0]} \u2013 {years[-1]}")
        elif years:
            _kv("Date Range", years[0])

    # ==================================================================
    #  FILE FORMATS
    # ==================================================================
    if extension_counts:
        _section("File Formats", CLR_AMBER)
        sorted_exts = sorted(extension_counts.items(), key=lambda x: -x[1])
        max_count = sorted_exts[0][1] if sorted_exts else 1
        for ext, cnt in sorted_exts:
            pct = round(cnt / file_count * 100, 1) if file_count else 0
            _check_page(17)
            cv.setFont("Helvetica-Bold", 8)
            cv.setFillColor(CLR_TEXT)
            cv.drawString(margin + 12, _y(), ext.upper())
            # Bar
            bar_x = margin + 60
            bar_w = content_w - 135
            cv.setFillColor(CLR_BAR_BG)
            cv.roundRect(bar_x, _y() - 1, bar_w, 9, 3, fill=1, stroke=0)
            fill_w = max(bar_w * (cnt / max_count), 6)
            cv.setFillColor(CLR_AMBER)
            cv.roundRect(bar_x, _y() - 1, fill_w, 9, 3, fill=1, stroke=0)
            # Count
            cv.setFont("Helvetica", 7.5)
            cv.setFillColor(CLR_MUTED)
            cv.drawRightString(page_w - margin, _y(), f"{cnt:,}  ({pct}%)")
            _move(17)

    # ==================================================================
    #  LOCATIONS
    # ==================================================================
    if locations:
        _section("Locations", CLR_GREEN)
        for loc in locations:
            parts = loc.replace("-", " ").split("/")
            _bullet(" > ".join(parts), CLR_GREEN)

    # ==================================================================
    #  TIMELINE
    # ==================================================================
    if date_info:
        _section("Timeline", CLR_BLUE)
        for yr in sorted(date_info.keys(), reverse=True):
            months_str = ", ".join(
                MONTH_NAMES.get(m, m) for m in sorted(date_info[yr])
            )
            _check_page(16)
            cv.setFont("Helvetica-Bold", 9)
            cv.setFillColor(CLR_BLUE)
            cv.drawString(margin + 12, _y(), yr)
            cv.setFont("Helvetica", 8.5)
            cv.setFillColor(CLR_MUTED)
            cv.drawString(margin + 50, _y(), months_str)
            _move(17)

    # ==================================================================
    #  PEOPLE
    # ==================================================================
    if people:
        _section("Enrolled People", CLR_PURPLE)
        for person in people:
            _bullet(person, CLR_PURPLE)

    # ==================================================================
    #  SUBFOLDERS
    # ==================================================================
    if subfolder_list:
        _section("Subfolders")
        for sf in sorted(subfolder_list)[:30]:
            _check_page(13)
            cv.setFont("Helvetica", 7.5)
            cv.setFillColor(CLR_MUTED)
            cv.drawString(margin + 12, _y(), sf)
            _move(13)
        if len(subfolder_list) > 30:
            _check_page(13)
            cv.setFont("Helvetica-Oblique", 7.5)
            cv.setFillColor(CLR_MUTED)
            cv.drawString(margin + 12, _y(), f"...and {len(subfolder_list) - 30} more")
            _move(13)

    # ── Finalize ──
    _footer()
    cv.save()
